-- Oracle Ebusiness Suite Schema (Mock)

-- General Ledger
CREATE TABLE gl_je_headers (
    je_header_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    je_name VARCHAR2(255) NOT NULL,
    status VARCHAR2(50),
    ledger_id NUMBER,
    period_name VARCHAR2(50)
);

CREATE TABLE gl_je_lines (
    je_line_num NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    je_header_id NUMBER REFERENCES gl_je_headers(je_header_id),
    code_combination_id NUMBER,
    accounted_dr NUMBER(15, 2),
    accounted_cr NUMBER(15, 2)
);

-- Payables
CREATE TABLE ap_invoices_all (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_num VARCHAR2(50) NOT NULL,
    vendor_id NUMBER, -- Intentional correlation with suppliers.supplier_id
    invoice_amount NUMBER(15, 2),
    invoice_date DATE
);

-- Seed Data
INSERT INTO gl_je_headers (je_name, status, ledger_id, period_name)
VALUES ('JE_JAN_2026', 'POSTED', 1, 'JAN-26');
INSERT INTO gl_je_lines (je_header_id, code_combination_id, accounted_dr, accounted_cr)
VALUES (1, 101, 1000.00, 0);
INSERT INTO gl_je_lines (je_header_id, code_combination_id, accounted_dr, accounted_cr)
VALUES (1, 102, 0, 1000.00);
INSERT INTO ap_invoices_all (invoice_num, vendor_id, invoice_amount, invoice_date)
VALUES ('INV-001', 1, 500.00, SYSDATE);
