-- JD Edwards Schema (Mock)

-- Address Book (Customers/Suppliers)
CREATE TABLE f0101 (
    an8 NUMBER PRIMARY KEY, -- Address Number (Identifier)
    alph VARCHAR2(255), -- Name
    atst VARCHAR2(10) -- Search Type (C = Customer, V = Vendor)
);

-- Account Ledger
CREATE TABLE f0911 (
    aid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    an8 NUMBER REFERENCES f0101(an8),
    doc NUMBER, -- Document Number
    dct VARCHAR2(2), -- Document Type
    mcu VARCHAR2(12), -- Business Unit
    obj VARCHAR2(6), -- Object Account
    aamt NUMBER(15, 2) -- Amount
);

-- Seed Data
INSERT INTO f0101 (an8, alph, atst)
VALUES (1001, 'Customer JDE 1', 'C');
INSERT INTO f0101 (an8, alph, atst)
VALUES (1002, 'Supplier JDE 1', 'V');
INSERT INTO f0911 (an8, doc, dct, mcu, obj, aamt)
VALUES (1001, 12345, 'JE', '  100', '1110', 1000.00);
