-- Oracle DB@GCP Schema (Financials & ERP)

-- ERP Core Tables
CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    country VARCHAR2(100)
);
CREATE TABLE purchase_orders (
    po_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id NUMBER REFERENCES suppliers(supplier_id),
    status VARCHAR2(50),
    total_amount NUMBER(15, 2),
    created_date DATE DEFAULT SYSDATE
);
CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id NUMBER REFERENCES purchase_orders(po_id),
    amount_paid NUMBER(15, 2),
    payment_status VARCHAR2(50),
    transaction_metadata VARCHAR2(4000),
    -- Represents a 768-D vector embedding of the transaction_metadata for anomaly detection
    metadata_vector VECTOR(768, FLOAT32)
);
-- Oracle Graph: Create a Property Graph to traverse Supplier connections
-- This allows Cypher-like MATCH (s:Supplier)-[:HAS_PO]->(p:PurchaseOrder) queries.
CREATE PROPERTY GRAPH erp_supply_graph VERTEX TABLES (
    suppliers KEY (supplier_id) LABEL Supplier,
    purchase_orders KEY (po_id) LABEL PurchaseOrder
) EDGE TABLE purchase_orders AS has_po
    KEY (po_id)
    SOURCE KEY (supplier_id) REFERENCES suppliers
    DESTINATION KEY (po_id) REFERENCES purchase_orders
    LABEL HAS_PO;
-- Create an AI Vector Index for similarity search
CREATE VECTOR INDEX invoice_meta_idx ON invoices(metadata_vector) ORGANIZATION NEIGHBOR GRAPH DISTANCE EUCLIDEAN;
-- Seed Data (Without explicit vectors for brevity in script)
INSERT INTO suppliers (name, country)
VALUES ('SupplierA', 'USA');
INSERT INTO suppliers (name, country)
VALUES ('SupplierB', 'Taiwan');