-- ===================================================================
-- Warehouse Supply Chain & Inventory Risk Spatial Schema
-- Based on Oracle AI Database & Graph/Spatial A2A Reference Model
-- ===================================================================

-- 1. Core Inventory & Warehouse Master Tables
CREATE TABLE warehouse_master (
    warehouse_id VARCHAR2(50) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location_geo SDO_GEOMETRY,
    capacity_utilization NUMBER(5,2),
    temperature_control VARCHAR2(10),
    sustainability_score NUMBER(3,1)
);

CREATE TABLE product_master (
    sku_id VARCHAR2(50) PRIMARY KEY,
    product_name VARCHAR2(200) NOT NULL,
    criticality VARCHAR2(20),
    unit_cost NUMBER(12,2),
    carbon_footprint_kg NUMBER(8,2)
);

CREATE TABLE inventory_levels (
    inventory_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    warehouse_id VARCHAR2(50) REFERENCES warehouse_master(warehouse_id),
    sku_id VARCHAR2(50) REFERENCES product_master(sku_id),
    stock_quantity NUMBER NOT NULL,
    reorder_threshold NUMBER NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Supply Chain Network Graph & Hotspot Tracking
CREATE TABLE supplier_master (
    supplier_id VARCHAR2(50) PRIMARY KEY,
    supplier_name VARCHAR2(100) NOT NULL,
    sustainability_rating VARCHAR2(10),
    lead_time_days NUMBER
);

CREATE TABLE supply_network_edges (
    edge_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    from_supplier_id VARCHAR2(50) REFERENCES supplier_master(supplier_id),
    to_sku_id VARCHAR2(50) REFERENCES product_master(sku_id),
    cost_per_unit NUMBER(12,2),
    currency VARCHAR2(3) DEFAULT 'USD'
);

CREATE TABLE spatial_risk_hotspots (
    hotspot_id VARCHAR2(50) PRIMARY KEY,
    warehouse_id VARCHAR2(50) REFERENCES warehouse_master(warehouse_id),
    risk_factor VARCHAR2(100),
    severity VARCHAR2(20),
    recommended_action VARCHAR2(300)
);

-- 3. Oracle Property Graph Definition
CREATE PROPERTY GRAPH supply_chain_graph
    VERTEX TABLES (
        supplier_master KEY(supplier_id)
            PROPERTIES(supplier_name, sustainability_rating),
        product_master KEY(sku_id)
            PROPERTIES(product_name, criticality),
        warehouse_master KEY(warehouse_id)
            PROPERTIES(name, capacity_utilization)
    )
    EDGE TABLES (
        supply_network_edges KEY(edge_id)
            SOURCE KEY(from_supplier_id) REFERENCES supplier_master(supplier_id)
            DESTINATION KEY(to_sku_id) REFERENCES product_master(sku_id)
            PROPERTIES(cost_per_unit, currency)
    );
